name: "Discord scrape (Bot API) → Supabase"

on:
  workflow_dispatch:
  schedule:
    # Daily at 12:00 UTC (~09:00 America/Santiago when UTC-3)
    - cron: "0 12 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      # ---- required secrets/vars ----
      DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CHANNEL_ID }}
      DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}

      SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:   ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:  ${{ secrets.SUPABASE_PWD }}

      # ---- optional tuning ----
      MAX_MESSAGES:  ${{ vars.MAX_MESSAGES }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libpq-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "httr2","dplyr","purrr","tidyr","lubridate","readr",
            "DBI","RPostgres","glue"
          ), repos="https://cloud.r-project.org")'

      - name: Run scraper (Bot API)
        run: Rscript discord_bot_scrape.R

      - name: Upload artifacts (CSV snapshot)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: discord-bot-scrape-artifacts
          path: artifacts/
          if-no-files-found: warn

